name: motivator
description: Simple Motivator project.

version: 0.0.1+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bloc: ^3.0.0
  cloud_firestore: ^0.13.4+2
  cupertino_icons: ^0.1.3
  equatable: ^1.1.1
  firebase_auth: ^0.15.2
  firebase_analytics: ^5.0.2
  firebase_core: ^0.4.0+9
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  flutter_form_bloc: ^0.12.3
  font_awesome_flutter: ^8.8.1
  form_bloc: ^0.12.0
  google_sign_in: ^4.2.0
  meta: ^1.1.8
  provider: ^4.0.4
  rxdart: "^0.23.1"
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
